async page => {
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width:1440,height:960});
 await page.goto('http://127.0.0.1:5177');
 await page.locator('#loading').waitFor({state:'detached'});await page.locator('[data-menu="options"]').click();await page.locator('[data-pref="language"]').selectOption('pl');await page.locator('[data-menu="main"]').click();
 await page.locator('[data-menu="new"]').click();await page.locator('[data-scenario="survival"]').click();
 await page.getByRole('button',{name:'Pauza / wznowienie',exact:true}).click();
 const check=async(fn,message)=>{if(!await page.evaluate(fn))throw Error(message)};
 await check(()=>window.folwark.scene.world.paused,'Pause failed');
 const time=await page.evaluate(()=>window.folwark.scene.world.time);
 await page.waitForTimeout(200);
 await check(()=>window.folwark.scene.world.paused,'Pause lost');
 await page.getByRole('button',{name:'Wybierz: Koniczyna',exact:true}).click();
 await check(()=>window.folwark.scene.selected[0]==='unit-101','Roster selection failed');
 await page.getByRole('button',{name:'Wysrodkuj mape',exact:true}).click();
 await page.getByRole('button',{name:'Przemiesc: wybierz miejsce na mapie',exact:true}).click();
 const pos=await page.evaluate(()=>{const c=window.folwark.scene.cameras.main;return{x:(1100-c.worldView.x)*c.zoom,y:(800-c.worldView.y)*c.zoom}});
 await page.locator('#game canvas').click({position:pos});
 await check(()=>window.folwark.scene.world.units[1].path.length>0,'Canvas move failed');
 const before=await page.evaluate(()=>window.folwark.scene.world.units[1].x);
 await page.getByRole('button',{name:'Pauza / wznowienie',exact:true}).click();
 await page.waitForTimeout(650);
 const after=await page.evaluate(()=>window.folwark.scene.world.units[1].x);
 if(before===after)throw Error('Unit did not move');
 await page.getByRole('button',{name:'Pauza / wznowienie',exact:true}).click();
 await page.getByRole('button',{name:'Zbieraj plony',exact:true}).click();
 await check(()=>window.folwark.scene.world.units[1].job==='harvest','Harvest order failed');
 await page.getByRole('button',{name:'Rozbudowa',exact:true}).click();
 await page.screenshot({path:'output/playwright/build-menu.png'});
 await page.locator('[data-build="well"]').click();
 await page.evaluate(()=>window.folwark.scene.cameras.main.centerOn(1100,850));await page.waitForTimeout(100);
 const spot=await page.evaluate(()=>{const c=window.folwark.scene.cameras.main;return{x:(1330-c.worldView.x)*c.zoom,y:(1030-c.worldView.y)*c.zoom}});
 await page.locator('#game canvas').click({position:spot});
 await check(()=>window.folwark.scene.world.buildings.length===14,'Construction placement failed');
 await page.getByRole('button',{name:'Zapisz gre',exact:true}).click();
 const wood=await page.evaluate(()=>window.folwark.scene.world.resources.wood);
 await page.evaluate(()=>{window.folwark.scene.world.resources.wood=0});
 await page.getByRole('button',{name:'Zapisy gry',exact:true}).click();
 await page.locator('[data-load-slot="quick"]').click();
 await page.evaluate(()=>{window.folwark.scene.world.paused=true});
 if(Math.abs(await page.evaluate(()=>window.folwark.scene.world.resources.wood)-wood)>.2)throw Error('Save/load failed');
 await page.getByRole('button',{name:'Rada',exact:true}).click();
 await page.getByRole('button',{name:'Przywileje rady',exact:true}).click();
 await check(()=>window.folwark.scene.world.politics.rationPolicy==='privileged','Policy change failed');
 await page.getByRole('button',{name:'Rowne racje',exact:true}).click();
 await page.locator('[data-action="feast"]').click();
 await page.evaluate(()=>{const w=window.folwark.scene.world;w.time=129.99;w.paused=false;w.tick(.1);window.folwark.scene.onChange()});
 await page.locator('dialog[open]').waitFor();
 await page.locator('[data-choice="0"]').click();
 await check(()=>window.folwark.scene.world.event===null,'Dilemma did not resolve');
 await page.getByRole('button',{name:'Ksiega folwarku',exact:true}).click();
 if(await page.locator('.gallery img').count()!==18)throw Error('Missing gallery assets');
 await page.locator('[data-art="cards-final"]').click();
 await page.locator('.full-art').evaluate(img=>img.decode());
 await page.getByRole('button',{name:'Zamknij',exact:true}).click();
 await page.getByRole('button',{name:'Wybor',exact:true}).click();
 await page.getByRole('button',{name:'Wybierz: Bokser',exact:true}).click();
 await page.getByRole('button',{name:'Wysrodkuj mape',exact:true}).click();
 await page.screenshot({path:'output/playwright/desktop.png'});
 const pixels=await page.evaluate(()=>new Promise(resolve=>{
   window.folwark.game.renderer.snapshot(img=>{
     const c=document.createElement('canvas');c.width=img.width;c.height=img.height;
     const ctx=c.getContext('2d');ctx.drawImage(img,0,0);
     const p=ctx.getImageData(0,0,c.width,c.height).data,s=new Set();
     for(let i=0;i<p.length;i+=400)s.add(p[i]+','+p[i+1]+','+p[i+2]);
     resolve(s.size);
   });
 }));
 if(pixels<80)throw Error('Canvas blank or assets not rendered: '+pixels);
 for(const [width,height]of [[390,844],[360,740],[1280,720]]){
   await page.setViewportSize({width,height});await page.waitForTimeout(250);
   await page.getByRole('button',{name:'Wysrodkuj mape',exact:true}).click();
   await check(()=>document.documentElement.scrollWidth<=innerWidth,'Horizontal overflow');
   await page.screenshot({path:'output/playwright/viewport-'+width+'.png'});
 }
 await page.setViewportSize({width:1440,height:960});
 await page.getByRole('button',{name:'Wysrodkuj mape',exact:true}).click();
 if(errors.length)throw Error(errors.join('\n'));
 return {passed:true,canvasColors:pixels,movement:{before,after},savedWood:wood,viewports:4,assets:18,errors};
}
