import { atlasStyle } from './Atlas';
import { buildingDefs, type World, type Building, type Resource } from '../simulation/World';
import { recipes, resourceNames, resourceArt, technologies, type Technology } from '../simulation/Development';
const icon=(name:string)=>'<i data-lucide="'+name+'"></i>';
const art=(key:string)=>'<span class="atlas" style="'+atlasStyle(key)+'"></span>';
const cost=(c:Partial<Record<Resource,number>>)=>Object.entries(c).map(([k,v])=>v+' '+resourceNames[k as Resource]).join(' / ');
export function buildingControls(w:World,b:Building){
 const workers=w.living.filter(a=>a.target===b.id&&a.job),recipe=recipes[b.kind];
 return '<div class="building-controls"><div class="detail-row"><span>Poziom '+b.level+'</span><span>'+workers.length+' pracownikow</span></div>'+
 (b.progress<1?'<meter max="1" value="'+b.progress+'"></meter><p>'+w.productionState(b)+'</p><div class="compact-actions"><button data-staff="'+b.id+'" title="Dodaj budowniczego">'+icon('user-plus')+'</button><button data-priority="'+b.id+'" title="Buduj jako pierwsze">'+icon('arrow-up-to-line')+'</button><button data-cancel-build="'+b.id+'" title="Anuluj budowe, zwrot 80% pozostalych materialow">'+icon('x')+'</button></div>':
 '<div class="compact-actions"><button data-staff="'+b.id+'" title="Przydziel pracownika" '+(!b.enabled||!recipe&&!['field','garden','orchard','lumber','quarry','pasture','barn'].includes(b.kind)?'disabled':'')+'>'+icon('user-plus')+'</button><button data-release="'+b.id+'" title="Zwolnij pracownikow z zadania">'+icon('user-minus')+'</button><button data-toggle-building="'+b.id+'" title="Wstrzymaj i zwolnij zaloge / wznow zaklad">'+icon(b.enabled?'pause':'play')+'</button><button data-upgrade="'+b.id+'" title="Ulepszenie: '+cost({wood:25*b.level,stone:15*b.level,tools:2*b.level})+'" '+(b.level>=3||!recipe&&!['field','garden','orchard'].includes(b.kind)?'disabled':'')+'>'+icon('chevrons-up')+'</button></div>')+
 (recipe?'<div class="recipe">'+cost(recipe.input)+'<strong>'+icon('arrow-down')+cost(recipe.output)+'</strong><meter max="'+recipe.seconds+'" value="'+b.production+'"></meter><small>'+w.productionState(b)+' / cykle: '+b.batches+'</small></div>':'')+
 (['field','garden','orchard','lumber','quarry'].includes(b.kind)?'<div class="detail-row"><span>Dostepne zasoby</span><b>'+Math.floor(b.stock)+'</b></div>':'')+
 workers.map(a=>'<button class="worker-row" data-unit="'+a.id+'">'+art('portrait-'+a.species)+'<span>'+a.name+'</span>'+icon('locate-fixed')+'</button>').join('')+'</div>';
}
export function economyPanel(w:World){
 const queue=w.buildings.filter(b=>b.progress<1).sort((a,b)=>a.priority-b.priority);
 return '<div class="economy-panel"><span class="eyebrow">GOSPODARKA</span><h2>Praca i zapasy</h2><div class="stock-table">'+(Object.keys(resourceNames) as Resource[]).map(k=>'<div>'+art(resourceArt[k])+'<span>'+resourceNames[k]+'</span><b>'+Math.floor(w.get(k))+'</b></div>').join('')+'</div><button class="wide-action" data-action="wool-bedding" '+(w.society.bedding>=3||w.resources.wool<12?'disabled':'')+'>'+icon('bed')+' Welna na poslania / 12 <small>'+w.society.bedding+'/3 / -10% opalu</small></button><h3>Kolejka budowy <small>'+queue.length+'</small></h3>'+
 (queue.length?queue.map(b=>'<div class="queue-row"><button data-focus-building="'+b.id+'">'+buildingDefs[b.kind].name+'</button><span>'+Math.floor(b.progress*100)+'%</span><button data-priority="'+b.id+'" title="Priorytet">'+icon('arrow-up')+'</button><button data-cancel-build="'+b.id+'" title="Anuluj">'+icon('x')+'</button><meter max="1" value="'+b.progress+'"></meter><small>'+w.productionState(b)+'</small></div>').join(''):'<p class="muted">Brak oczekujacych budow.</p>')+
 '<h3>Zaklady produkcyjne</h3>'+w.buildings.filter(b=>recipes[b.kind]).map(b=>'<div class="factory-row"><button data-focus-building="'+b.id+'">'+art(buildingDefs[b.kind].art)+'<span>'+buildingDefs[b.kind].name+'<small>'+w.productionState(b)+'</small></span></button><button data-staff="'+b.id+'" title="Przydziel pracownika">'+icon('user-plus')+'</button></div>').join('')+'</div>';
}
export function researchPanel(w:World){
 return '<div class="research-panel"><span class="eyebrow">ROZWOJ WSPOLNOTY</span><h2>Wiedza zmienia prace</h2><div class="detail-row"><span>Biblioteki: '+w.count('library')+'</span><b>'+Math.floor(w.resources.knowledge)+' wiedzy</b></div>'+
 (Object.keys(technologies) as Technology[]).map(key=>{const t=technologies[key],done=w.research.includes(key);return '<article><h3>'+t.name+'</h3><p>'+t.description+'</p><small>'+cost(t.cost)+'</small><button data-research="'+key+'" '+(done||!w.count('library')||!w.canPay(t.cost)?'disabled':'')+'>'+icon(done?'check':'book-open')+(done?'Ukonczone':!w.count('library')?'Wymaga biblioteki':'Rozpocznij badanie')+'</button></article>'}).join('')+'</div>';
}
export function tradePrice(w:World,k:Resource){const q=w.tradeQuote(k);return q.amount+' '+resourceNames[k]+' / kupno: '+q.buy+' monet / sprzedaz: '+q.sell+' monet'}
export function lawsPanel(w:World,choice:Resource='wood'){
 const fields=[['work','Rytm pracy',[['rested','Krotszy dzien'],['balanced','Zrownowazony'],['intensive','Mobilizacja']]],['tax','Podatki',[['low','Niskie'],['normal','Zwykle'],['high','Wysokie']]],['food','Wielkosc posilkow',[['saving','Oszczedne'],['normal','Zwykle'],['generous','Obfite']]],['forest','Gospodarka lesna',[['sustainable','Odnawialna'],['intensive','Intensywny wyreb']]]] as const;
 return '<h3>Prawa gospodarcze</h3><div class="law-controls">'+fields.map(([key,label,options])=>'<label><span>'+label+'</span><select data-law="'+key+'" aria-label="'+label+'">'+options.map(([value,name])=>'<option value="'+value+'" '+(w.laws[key]===value?'selected':'')+'>'+name+'</option>').join('')+'</select></label>').join('')+'</div><div class="policy-impact">Wydajnosc pracy '+Math.round(w.workRate*100)+'% / zmeczenie '+Math.round(w.workFatigue*100)+'%</div><h3>Rynek surowcow</h3><div class="trade-controls"><select id="trade-resource" aria-label="Surowiec do wymiany">'+(['wood','stone','flour','bread','tools','milk','eggs','wool','herbs'] as Resource[]).map(k=>'<option value="'+k+'" '+(choice===k?'selected':'')+'>'+resourceNames[k]+'</option>').join('')+'</select><button data-action="trade-buy" title="Kup 40 jednostek, narzedzia: 10">'+icon('shopping-cart')+'</button><button data-action="trade-sell" title="Sprzedaj 40 jednostek, narzedzia: 10">'+icon('coins')+'</button></div><p id="trade-price" class="muted">'+tradePrice(w,choice)+'</p>';
}
